### ISSUE TITLE
Add accessibility matcher function module

### ISSUE THREAD

**Issue by gtyrkicksin216** [gtyrkicksin216/fulcrum-css#40]
Add accessibility contrast matcher for text calculated based on the background color passed in

```scss
@use 'sass:color';

@function contrastMatcher ($hex) {
  $color: null;
  // add error handling
  $red: color.red($hex);
  $green: color.green($hex);
  $blue: color.blue($hex);
  $threshold: 0.5;
  $borderThreshold: 0.8;

  // $background: rgb($red, $green, $blue);
  // NOTE: percieved lightness maths
  $_red: $red * 0.2126;
  $_green: $green * 0.7152;
  $_blue: $blue * 0.0722;

  $sum: $_red + $_green + $_blue;

  $percievedLightness: $sum / 255;

  $color: hsl(0, 0%, (($percievedLightness - $threshold) * -10000000%));
  @debug $color;

  @return $color;
}
```
